spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java_shop?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server.port: 9100
server.servlet.context-path: /api

BASE_LOCATION: D:\projects\java_shop
DB_NAME: shop

  #BASE_LOCATION: C:\Users\Administrator\Desktop\java-shop
#DB_NAME: java_shop


File:
#  uploadPath: ${BASE_LOCATION}\server\upload
  uploadPath: \server\upload

mybatis:
  configuration:
    map-underscore-to-camel-case: true
# log
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
logging:
  level:
    com.pigo.shop.mapper: debug